CREATE TABLE REPORT_SUPPLIER_ORDERS_DETAILS (
    SUPPLIER_NAME VARCHAR2(100),
    SUPPLIER_CONTACT_NAME VARCHAR2(17),
    SUPPLIER_CONTACT1 VARCHAR2(100),
    SUPPLIER_CONTACT2 VARCHAR2(13),
    TOTAL_ORDERS INTEGER,
    ORDER_TOTAL_AMOUNT VARCHAR2(20)
);