/*
    AUTHOR  : NISHTABYE ITTOO
    PURPOSE : List all suppliers with their respective number of orders and total amount ordered from them between the period of 01 January 2022 and 31 August 2022.
 */


CREATE OR REPLACE PROCEDURE TEST.GETSUPPLIERORDERDETAILSPROCEDURE
AS

CURSOR data_cursor IS
SELECT
    pod.SUPPLIER_NAME AS Supplier_Name,
    sd.SUPP_CONTACT_NAME AS Supplier_Contact_Name,
    CASE
        WHEN LENGTH(sd.SUPP_MOBILE_NUMBER) = 8 THEN
            SUBSTR(sd.SUPP_MOBILE_NUMBER, 1, 4) || '-' || SUBSTR(sd.SUPP_MOBILE_NUMBER, 5)
        ELSE
            sd.SUPP_MOBILE_NUMBER
    END AS Supplier_Contact_No1,
    CASE
        WHEN LENGTH(sd.SUPP_PHONE_NUMBER) = 7 THEN
            SUBSTR(sd.SUPP_PHONE_NUMBER, 1, 3) || '-' || SUBSTR(sd.SUPP_PHONE_NUMBER, 4)
        ELSE
            sd.SUPP_PHONE_NUMBER
    END AS Supplier_Contact_No2,
    COUNT(DISTINCT pod.ORDER_REFERENCE) AS NUMBER_OF_ORDERS,
    SUM(DISTINCT(TO_NUMBER(REPLACE(pod.ORDER_TOTAL_AMOUNT, ',', '')))) AS TOTAL_ORDER_AMOUNT
FROM
    PURCHASE_ORDER_DETAILS_VIEW pod
    INNER JOIN SUPPLIER_DATA sd ON UPPER(pod.SUPPLIER_NAME) = UPPER(sd.SUPPLIER_NAME)
 WHERE  pod.ORDER_PERIOD BETWEEN TO_DATE('2022-01-01', 'YYYY-MM-DD') AND TO_DATE('2022-08-31', 'YYYY-MM-DD')
GROUP BY
    pod.SUPPLIER_NAME, sd.SUPP_CONTACT_NAME, sd.SUPP_MOBILE_NUMBER, sd.SUPP_PHONE_NUMBER
ORDER BY
    NUMBER_OF_ORDERS DESC;





count_table INTEGER;

BEGIN
	SELECT count(*)
	INTO count_table
	FROM REPORT_SUPPLIER_ORDERS_DETAILS;

	IF count_table > 0 THEN
		DELETE FROM REPORT_SUPPLIER_ORDERS_DETAILS;
	END IF;


	FOR rec IN data_cursor LOOP

		INSERT INTO REPORT_SUPPLIER_ORDERS_DETAILS (SUPPLIER_NAME, SUPPLIER_CONTACT_NAME, SUPPLIER_CONTACT1, SUPPLIER_CONTACT2, TOTAL_ORDERS, ORDER_TOTAL_AMOUNT)
		VALUES(rec.Supplier_Name, rec.Supplier_Contact_Name, rec.Supplier_Contact_No1, rec.Supplier_Contact_No2, rec.NUMBER_OF_ORDERS, TO_CHAR(rec.TOTAL_ORDER_AMOUNT , '99,999,990.00'));
	END LOOP;

END;
