CREATE TABLE ORDER_SUMMARY(
    ORDER_REF VARCHAR2(5) PRIMARY KEY,
    ORDER_DATE DATE NOT NULL,
    SUPPLIER_ID INTEGER NOT NULL, CONSTRAINT fk_supplier FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER_DATA(SUPPLIER_ID),
    ORDER_TOTAL_AMOUNT NUMBER(20) NOT NULL,
    ORDER_DESCRIPTION VARCHAR2(100) NOT NULL,
    ORDER_STATUS VARCHAR2(10) NOT NULL CONSTRAINT chk_order_staus CHECK (ORDER_STATUS IN ('Open', 'Closed'))
);