CREATE VIEW Purchase_Order_Details_View
AS
SELECT TO_NUMBER(REPLACE(os.ORDER_REF ,'PO','')) AS Order_Reference ,
os.ORDER_DATE AS ORDER_PERIOD,
INITCAP(SD.SUPPLIER_NAME) AS SUPPLIER_NAME, TO_CHAR(os.ORDER_TOTAL_AMOUNT , '9,999,999.00') AS ORDER_TOTAL_AMOUNT,
os.ORDER_STATUS AS Order_Status,ip.INVOICE_REFERENCE AS Invoice_Reference ,ip.INVOICE_AMOUNT AS Invoice_Amount, ip.INVOICE_STATUS AS Invoice_Status
FROM ORDER_SUMMARY os
INNER JOIN SUPPLIER_DATA sd ON os.SUPPLIER_ID = sd.SUPPLIER_ID
INNER JOIN ORDER_LINE_DETAILS old2 ON os.ORDER_REF  = OLD2.ORDER_PARENT_REF
INNER JOIN INVOICE_PAYMENT ip ON OLD2.ORDER_LINE_ID = ip.ORDER_LINE_ID
GROUP BY Order_Reference, ORDER_PERIOD,SUPPLIER_NAME,ORDER_TOTAL_AMOUNT,os.ORDER_STATUS,Invoice_Reference,Invoice_Amount, Invoice_Status
ORDER BY Order_Reference;

CREATE TABLE REPORT_PURCHASE_ORDERS_INVOICES (
     ORDER_REFERENCE NUMBER,
     ORDER_PERIOD VARCHAR2(17),
     SUPPLIER_NAME VARCHAR2(100),
     ORDER_TOTAL_AMOUNT VARCHAR2(13),
     ORDER_STATUS VARCHAR2(50),
     INVOICE_REFERENCE VARCHAR2(50),
     INVOICE_TOTAL_AMOUNT VARCHAR2(13),
     ACTION VARCHAR2(25)
);
